insert into hashtag1 (hashNum,clickCount, hashName) values ('1001',0, '귀여워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1002',0, '귀호강');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1003',0, '꺄 신나요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1004',0, '꿀잼');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1005',0, '끝날 때까지 끝난 게 아니야');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1006',0, '놀라워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1007',0, '눈 감아도 아른아른');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1008',0, '눈물나게 감동이에요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1009',0, '눈호강');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1010',0, '대박!');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1011',0, '두근두근 설레요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1012',0, '따뜻해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1013',0, '멋져요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1014',0, '박장대소');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1015',0, '벅차요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1016',0, '부끄부끄');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1017',0, '사랑스러워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1018',0, '소소해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1019',0, '스트레스 풀려요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1020',0, '애틋해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1021',0, '유쾌상쾌통쾌');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1022',0, '정말 최고예요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1023',0, '즐거워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1024',0, '취향저격');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1025',0, '킬링타임');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1026',0, '평화로워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1027',0, '핑크빛 세상');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1028',0, '하트 뿅뿅 심쿵했어요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1029',0, '하하 빵터졌어요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1030',0, '행복해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1031',0, '헉 이럴 수가');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1032',0, '헤헷 좋아요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('1033',0, '훈훈해요');

insert into hashtag1 (hashNum,clickCount, hashName) values ('2001',0, '외로워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2002',0, '이불킥');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2003',0, '영혼까지 털렸어요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2004',0, '완전 멘붕');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2005',0, '눈물이 주룩주룩');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2006',0, '정말 울고 싶어요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2007',0, '뒤숭숭해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2008',0, '화가 난다 화가 나');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2009',0, '극혐');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2010',0, '짜증나요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2011',0, '답답해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2012',0, '식은땀 줄줄');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2013',0, '충격이에요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2014',0, '실망이에요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2015',0, '어이없어요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2016',0, '아쉬워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2017',0, '무서워요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2018',0, '섬뜩해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2019',0, '이게 뭐야 이게!');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2020',0, '아무 생각 없어요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2021',0, '고독해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2022',0, '식상해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2023',0, '김빠진 콜라');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2024',0, '따분해요');
insert into hashtag1 (hashNum,clickCount, hashName) values ('2025',0, '지루해요');